# Generated by Django 5.0.6 on 2024-07-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_useregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useregister',
            name='age',
        ),
    ]
